use utoipa::OpenApi;

/// LLMux 网关 API 文档。paths/components 由各 route 的 #[utoipa::path] 与
/// core 结构体的 ToSchema 自动收集。
#[derive(OpenApi)]
#[openapi(
    info(
        title = "LLMux Gateway API",
        version = "0.3.3",
        description = "本地单用户 AI 网关：账户、厂商、路由别名、网关鉴权、用量监控。"
    ),
    paths(
        crate::routes::accounts::list_accounts,
        crate::routes::accounts::create_account,
        crate::routes::accounts::update_account,
        crate::routes::accounts::delete_account,
        crate::routes::vendors::list_vendors,
        crate::routes::vendors::create_vendor,
        crate::routes::vendors::update_vendor,
        crate::routes::vendors::delete_vendor,
        crate::routes::keys::list_api_keys,
        crate::routes::keys::create_api_key,
        crate::routes::keys::update_api_key,
        crate::routes::keys::delete_api_key,
        crate::routes::models::aliases::get_model_aliases,
        crate::routes::models::aliases::set_model_alias,
        crate::routes::models::aliases::delete_model_alias,
        crate::routes::models::available::get_available_models,
        crate::routes::models::health::get_models_health,
        crate::routes::usage::get_activity,
        crate::routes::settings::get_settings,
        crate::routes::settings::update_settings,
        crate::routes::settings::purge_database,
        crate::routes::settings::export_config,
        crate::routes::settings::import_config,
        crate::routes::auth::handle_web_session,
        crate::routes::accounts::export_account_usage,
        crate::routes::models::testing::get_test_queue_status,
        crate::routes::models::testing::start_test_queue,
        crate::routes::models::testing::test_model,
        crate::routes::health::get_health_status,
        crate::routes::system::get_installed_tools,
        crate::routes::system::claude::get_claude_settings,
        crate::routes::system::claude::apply_claude_settings,
        crate::routes::system::claude::list_claude_backups,
        crate::routes::system::claude::restore_claude_backup,
        crate::routes::system::claude::delete_claude_backup,
        crate::routes::system::codex::get_codex_settings,
        crate::routes::system::codex::apply_codex_settings,
        crate::routes::system::codex::list_codex_backups,
        crate::routes::system::codex::restore_codex_backup,
        crate::routes::system::codex::delete_codex_backup,
        crate::routes::system::gemini::get_gemini_settings,
        crate::routes::system::gemini::apply_gemini_settings,
        crate::routes::system::gemini::list_gemini_backups,
        crate::routes::system::gemini::restore_gemini_backup,
        crate::routes::system::gemini::delete_gemini_backup,
        crate::routes::v1::openai::chat_completions,
        crate::routes::v1::openai::responses,
        crate::routes::v1::anthropic::messages,
        crate::routes::v1::models::models,
        crate::routes::v1::gemini::gemini,
    ),
    components(schemas(
        llmux_core::models::Vendor,
        llmux_core::models::AccountPublic,
        llmux_core::models::ApiKey,
        llmux_core::models::ModelAlias,
        llmux_core::models::SettingRow,
        crate::routes::models::aliases::AliasResponse,
        crate::routes::models::aliases::AliasAccountSummary,
        crate::routes::usage::ActivityQuery,
        crate::routes::system::helpers::BackupQuery,
    ))
)]
pub struct ApiDoc;
