[package]
name = "llmux"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "llmux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
llmux-core = { path = "../llmux-core" }
llmux-server = { path = "../llmux-server" }
time.workspace = true
ratatui.workspace = true
crossterm.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
